name: Build Windows Application

  on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

  permissions:
    contents: write

  jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
        - run: npm install --legacy-peer-deps
        - run: npm run build
          env:
            NODE_ENV: production
        - run: npx electron-builder --win --publish never
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/upload-artifact@v4
          with:
            name: MyLab-LIMS-Windows
            path: dist/*.exe
        - uses: softprops/action-gh-release@v2
          with:
            tag_name: "v3.0.0"
            files: dist/*.exe
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  